[package]
name = "wax-core"
version = "0.1.0"
edition = "2024"
license.workspace = true
description.workspace = true

[dependencies]
impl-trait-for-tuples = "0.2.3"
wasm-encoder.workspace = true
wasmparser.workspace = true
